name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: 'echo "$BOT_CONFIG" > ./src/bot-config.ts'
      shell: bash
      env:
        BOT_CONFIG: ${{secrets.BOT_CONFIG}}
    - run: 'echo "$FIREBASE_CONFIG" > ./src/firebase-config.ts'
      shell: bash
      env:
        FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}
    - run: 'echo "$SERVICE_ACCOUNT_JSON" > ./src/service-account.json'
      shell: bash
      env:
        SERVICE_ACCOUNT_JSON: ${{secrets.SERVICE_ACCOUNT_JSON}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adrorodri/classroom-bot
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: adrorodri/classroom-bot
        tag_with_ref: true
